### ISSUE TITLE
nice, but same thing we can get it over ipinfo right ?

### ISSUE THREAD

**Issue by neeltom92** [yousafkhamza/ipstack-containerization-with-nginx-lb#1]
curl ipinfo.io/8.8.8.8
{
  "ip": "8.8.8.8",
  "hostname": "dns.google",
  "anycast": true,
  "city": "Mountain View",
  "region": "California",
  "country": "US",
  "loc": "37.4056,-122.0775",
  "org": "AS15169 Google LLC",
  "postal": "94043",
  "timezone": "America/Los_Angeles",
  "readme": "https://ipinfo.io/missingauth"
}

**Comment by yousafkhamza** [comment]
Yeah, we can get the same on ipinfo without any API key required. I'm just using the python request module to grab the IP details through an API that is much better to get so many details. 
 
Thank you for your valuable comment  @neeltom92. Actually, I didn't notice the ipinfo.io so let me try the same with the subprocess module 

<img width="620" alt="Screenshot_2" src="https://user-images.githubusercontent.com/31238282/126089317-d94ee042-3efc-46c6-bc7f-76d8db321860.png">
<img width="903" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31238282/126089319-5541c313-ceb3-4670-a172-b98485ae2e96.png">
