### ISSUE TITLE
Avoid saving the secret keys in Git

### ISSUE THREAD

**Issue by feyzee** [yousafkhamza/ipstack-containerization-with-nginx-lb#2]
The secret key is open to everyone in the file `env.dev`. Add it to the `.gitignore` file before committing.

There are malicious bots all over GitHub crawling for credentials.

**Comment by yousafkhamza** [comment]
That's not the actual secret key and I just put the same here as a demonstration. Also, once we use .gitignore that file not be here. @stellarexplosions anyway thanks for your suggestion and I just edited the file. :)
